### ISSUE TITLE
rvmm-config should not include/exclude microg patches 

### ISSUE THREAD

**Issue by 0xNaimulHasanTaky** [j-hc/rvmm-config-gen#3]
[run](https://github.com/0xNaimulHasanTaky/ReVanced-Actions/actions/runs/7771409156/job/21192674356#step:6:36)
utils.sh [-] You cant include/exclude microg patches as that's done by rvmm builder automatically.
![Screenshot_2024-02-04-14-22-26-34](https://github.com/j-hc/rvmm-config-gen/assets/147870580/2110fdc7-c9d8-4eb6-968e-a38d230112c9)

**Comment by j-hc** [comment]
id rather have it show every patch. and that warning should be fixed by the user.
