### ISSUE TITLE
(Possible bug?) RVMM Can not read `dev` branch

### ISSUE THREAD

**Issue by cyberboh** [j-hc/rvmm-config-gen#4]
Hello ~
I add `revanced/revanced-patches/dev` in the patches source but likely it's not working. It should read dev branch for YouTube. In the dev branch there is bumped base to `19.09.37` but on RVMM config it still on `19.04.37` like this screenshot

![image](https://github.com/j-hc/rvmm-config-gen/assets/99109969/b3503b0a-f476-4a06-af22-3e36ad60496d)

Dev branch patches for reference: https://github.com/ReVanced/revanced-patches/releases/tag/v4.4.0-dev.5

**Comment by j-hc** [comment]
it does read dev branch but revanced-patches repo dont update patches.json on master anymore.
i could fetch the patches.json from releases section but github disallow it with CORS so there is not much to do here.

**Comment by j-hc** [comment]
it does read dev branch but revanced-patches repo doesnt update patches.json there anymore.
i could fetch the patches.json from releases section but github disallow it with CORS so there is not much i can do here.

**Comment by cyberboh** [comment]
> it does read dev branch but revanced-patches repo doesnt update patches.json there anymore. i could fetch the patches.json from releases section but github disallow it with CORS so there is not much i can do here.

Github sucks nowadays.
Is there any method to bypass CORS?

**Comment by j-hc** [comment]
> > it does read dev branch but revanced-patches repo doesnt update patches.json there anymore. i could fetch the patches.json from releases section but github disallow it with CORS so there is not much i can do here.
> 
> Github sucks nowadays.
> Is there any method to bypass CORS? 

not from the client side unless you modify your browser

**Comment by j-hc** [comment]
switched to using revanced api and added an option to upload your patches.json you can use that for dev branch
