### ISSUE TITLE
[Suggestion] Move to revanced api for patches?

### ISSUE THREAD

**Issue by fynks** [j-hc/rvmm-config-gen#5]
First of all thank you very much for your wonderful work.

I'm totally noob in coding but i've seen that [RVMM Config Generator](https://j-hc.github.io/rvmm-config-gen/) depends upon [`patches.json`](https://github.com/ReVanced/revanced-patches/blob/main/patches.json) from revanced-patches gtihub repo, which was last updated 2 months ago.

My Suggestion is that for revanced-patches we can you official [Revanced-API](https://api.revanced.app/). It's updated with each release and provides fresh patches information.

- Patches for revaned/revanced-patches can be obtained by using this url:
https://api.revanced.app/v2/patches/latest

**Comment by j-hc** [comment]
i would but that would make patch sources other than revanced unusable in rvmm-config-gen.
i could fetch the patches.json from releases section but github disallow it with CORS so there is not much i could do here

**Comment by j-hc** [comment]
https://github.com/j-hc/rvmm-config-gen/issues/4
