### ISSUE TITLE
Cant fetch patches.json automatically

### ISSUE THREAD

**Issue by soredake** [j-hc/rvmm-config-gen#6]
Probably because request to `https://api.revanced.app/v2/patches/latest` returns 403.

**Comment by Kerkpower** [comment]
ive noticed this too on multiple browsers and devices

**Comment by j-hc** [comment]
you can use the upload json button

**Comment by soredake** [comment]
@j-hc I think this should be closed as "wontfix", as nothing is solved as of now

**Comment by j-hc** [comment]
> @j-hc I think this should be closed as "wontfix", as nothing is solved as of now

its not a _wontfix_, its a _cantfix_ because revanced api enabled CORS stuff.

**Comment by soredake** [comment]
@j-hc didn't know about this, sorry, perhaps there should be a link to patches.json and a message that will user to save it and use "upload patches.json" button.
